name: stack-utils
base: core24
summary: Utilities for selecting hardware optimised engines
description: |
  These utilities help decide which components should be installed on a particular system.

grade: devel
confinement: strict
adopt-info: version

plugs:
  intel-npu:
    interface: custom-device
    custom-device: intel-npu-device
  npu-libs:
    interface: content
    content: npu-libs-2404
    target: $SNAP/npu-libs

layout:
  # OpenCL looks in /etc/OpenCL/vendors for .icd files containing the paths to shared objects
  /etc/OpenCL/vendors:
    bind: $SNAP/etc/OpenCL/vendors
  # Intel icd files use an absolute path to Intel OpenCL shared objects. Use a layout to mount the so files at the expected location
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl
  # Under wsl the libraries are expected in /usr/lib/wsl
  /usr/lib/wsl:
    bind: $SNAP_COMMON/usr/lib/wsl

environment:
  # Path to access current revision of components
  SNAP_COMPONENTS: /snap/$SNAP_INSTANCE_NAME/components/$SNAP_REVISION

parts:
  version:
    plugin: dump
    source: .
    build-packages:
      - git-lfs
    override-pull: |
      craftctl set version="$(git -C $SNAPCRAFT_PROJECT_DIR describe --always --dirty)"

  local-scripts:
    source: snap/local
    plugin: dump
    organize:
      "server.sh": bin/
      "server-webui.sh": bin/

  completer:
    source: completer
    plugin: dump
    organize:
      "snap.bash": bin/completion.bash

  engines:
    plugin: dump
    source: test_data/engines
    organize:
      "*": engines/

  runtimes:
    plugin: dump
    source: test_data/runtimes
    organize:
      "*": runtimes/

  models:
    plugin: dump
    source: test_data/models
    organize:
      "*": models/

  cli:
    plugin: go
    build-snaps:
      - go/1.26/stable
    source: .
    source-type: local
    override-build: |
      craftctl default
      # For tab completion
      ln --symbolic ./modelctl $CRAFT_PART_INSTALL/bin/stack-utils

  cli-dependencies:
    plugin: nil
    stage-packages:
      - pciutils # lspci
      - clinfo # used for Intel GPU vRAM detection. It depends on intel-opencl-icd

  # Used for NVIDIA vRAM and CUDA Capability detection.
  # Only the binary is included to avoid staging libraries, which should instead be provided by the host through the opengl interface.
  cli-nvidia-smi:
    plugin: nil
    build-packages:
      - nvidia-utils-580
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      cp /usr/bin/nvidia-smi $CRAFT_PART_INSTALL/usr/bin/
      
      license_dir=$CRAFT_PART_INSTALL/usr/share/doc/nvidia-utils-580/
      mkdir -p $license_dir
      cp /usr/share/doc/nvidia-utils-580/copyright $license_dir/

  # OpenCL ICD and libigdgmm are required for Intel GPU vRAM lookup with clinfo
  cli-intel-opencl-icd:
    plugin: nil
    build-packages:
      - wget
    override-build: |
      if [ "$CRAFT_ARCH_BUILD_FOR" == "amd64" ]; then
        # Legacy
        wget -nv https://github.com/intel/compute-runtime/releases/download/24.35.30872.36/intel-opencl-icd-legacy1_24.35.30872.36_amd64.deb
        wget -nv https://github.com/intel/compute-runtime/releases/download/24.35.30872.36/libigdgmm12_22.5.0_amd64.deb
      
        # Latest
        wget -nv https://github.com/intel/compute-runtime/releases/download/26.01.36711.4/intel-opencl-icd_26.01.36711.4-0_amd64.deb
        wget -nv https://github.com/intel/compute-runtime/releases/download/26.01.36711.4/libigdgmm12_22.9.0_amd64.deb
      
        dpkg --root=$CRAFT_PART_INSTALL --force-all -i *.deb
      
        # Two symlinks are created when installing intel-opencl-icd-legacy: 
        # etc/alternatives/ocloc -> /usr/bin/ocloc-24.35.0, usr/bin/ocloc -> /etc/alternatives/ocloc
        # These point to outside of the snap and fails store review. They are not required, so remove it.
        rm $CRAFT_PART_INSTALL/etc/alternatives/ocloc
        rm $CRAFT_PART_INSTALL/usr/bin/ocloc
      fi
      
      craftctl default

  webui:
    plugin: dump
    source: https://github.com/canonical/inference-snaps-webui/releases/download/v1.0.0-beta.5/inference-snaps-webui.tar.xz
    organize:
      "*": webui/

  mock-openai-server:
    plugin: dump
    source: test_data/mock-openai-server
    organize:
      "*": bin/mock-openai-server/

components:
  #
  # Runtimes
  #

  runtime-llama-cpp-cpu: &test-component
    type: standard
    summary: Just a test component
    description: Component for testing purposes
  runtime-llama-cpp-cuda:
    <<: *test-component
  runtime-llama-cpp-rocm:
    <<: *test-component
  runtime-openvino-model-server:
    <<: *test-component

  #
  # Models
  #
  model-4b-it-int4-fq-ov:
    <<: *test-component
  model-26b-a4b-q4-k-m-gguf:
    <<: *test-component
  mmproj-26b-bf16-gguf:
    <<: *test-component
  model-30b-a3b-q4-k-m-gguf-1-of-6:
    <<: *test-component
  model-30b-a3b-q4-k-m-gguf-2-of-6:
    <<: *test-component
  model-30b-a3b-q4-k-m-gguf-3-of-6:
    <<: *test-component
  model-30b-a3b-q4-k-m-gguf-4-of-6:
    <<: *test-component
  model-30b-a3b-q4-k-m-gguf-5-of-6:
    <<: *test-component
  model-30b-a3b-q4-k-m-gguf-6-of-6:
    <<: *test-component

apps:
  stack-utils:
    command: bin/modelctl
    completer: bin/completion.bash
    plugs:
      - hardware-observe
      - home
      - network
      - network-bind # for serving webui 
      - opengl
      - desktop # for xdg-open
    environment:
      ADDITIONAL_FEATURES: chat, webui

  clinfo:
    plugs:
      - hardware-observe
      - opengl
      - network
    command: usr/bin/clinfo

  nvidia-smi:
    plugs:
      - hardware-observe
      - opengl
    command: usr/bin/nvidia-smi

  server:
    command: bin/server.sh
    daemon: simple
    plugs:
      - network-bind

  server-webui:
    command: bin/server-webui.sh
    daemon: simple
    plugs:
      - network-bind
