name: Snap CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

env:
  SNAP_NAME: stack-utils

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.x'

      - name: Run tests
        run: go test -v ./...

  build:
    name: Build
    needs: [ test ]
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{env.SNAP_NAME}}_${{github.run_number}}_${{runner.arch}}
          path: ${{ steps.snapcraft.outputs.snap }}
          if-no-files-found: error

      - name: Publish snap
        uses: snapcore/action-publish@v1
        if: github.ref == 'refs/heads/main'
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: latest/edge/ci
